from RetrieveData import RETRIEVING_DATA_TEST
from CartWithHighestValue import CARTS_VALUE_PRODUCT_NOTFOUND_TEST_CASE,CARTS_VALUE_FROM_LINK_TEST_CASE,CARTS_VALUE_EXAMPLE_THAT_WORKS_TEST_CASE,CARTS_VALUE_USER_NOTFOUND_TEST_CASE
from FurthestUsers import FURTHEST_USERS_TEST
from ProductCategories import CATEGORIES_TEST


if __name__ == '__main__':

   RETRIEVING_DATA_TEST()
   print()
   print()

   CATEGORIES_TEST()
   print()
   print()

   CARTS_VALUE_FROM_LINK_TEST_CASE()
   CARTS_VALUE_EXAMPLE_THAT_WORKS_TEST_CASE()
   CARTS_VALUE_PRODUCT_NOTFOUND_TEST_CASE()
   CARTS_VALUE_USER_NOTFOUND_TEST_CASE()
   print()


   FURTHEST_USERS_TEST()



